[package]
name = "jason"
version = "0.1.0"
edition = "2021"

[lib]
name = "jason"
path = "src/lib.rs"

[[bin]]
name = "scratch"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-xid = "0.2.4"
